<a href="https://colab.research.google.com/github/Mrsenjiii/Numpy_reopsitory/blob/main/broadcasting.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:

import numpy as np
# a = list(range(10000))
import time
# l= list(range()10000000)
l= list(range(1000000))
a = time.time()
l = l[0:len(l)//2]

b = time.time()
print(b-a)
print(l[-1])

0.015079736709594727
499999


In [ ]:
a = 14
print(a%10)
print(a//10)

4
1


In [ ]:
Y = np.array([1,2,3,4,5,6])  # shape (6,) ==> (1,6) ==>   (1,6) (6,4) ==>
X = np.ones((6,4)) # 6,4
YX_ = Y@X      # 6,    6,4 => 1,6   6,4
# YX_.shape
YX_.shape

# c = Y + X
# c.shape

ValueError: ignored

In [ ]:
b = np.array([1,2,3,5])
c = np.ones((2,4))
# bc  =

In [ ]:
import numpy as np

A = np.array([[1, 2, 3],
              [4, 5, 6]])

B = np.array([2, 3, 4])
b = np.array([[2,3,4] ,[2,3,4]]) # B will be converted to this

C = A * B
d = A*b
print(A.shape, "\n", B.shape)
print(C)
print(d)

(2, 3) 
 (3,)
[[ 2  6 12]
 [ 8 15 24]]
[[ 2  6 12]
 [ 8 15 24]]


In [ ]:
import numpy as np
A = np.array([[1],
              [2],
              [3]])

B = np.array([2, 3, 4])
# A = (3,1)  and B  (3,)
# B => ()
print( "B shape " , B.shape )
print( "A shape " , A.shape )
print("after broadcasting  A and B will be of shape  ( 3,1 ) , (1,3)" ) # now we can perform multiplication
C = A * B

print(C)

B shape  (3,)
A shape  (3, 1)
[[ 2  3  4]
 [ 4  6  8]
 [ 6  9 12]]


In [ ]:
import numpy as np

A = np.array([[1, 2, 3],
              [4, 5, 6]])

B = np.array([[2],
              [3]])
print( "B shape " , B.shape )
print( "A shape " , A.shape )
print("after broadcasting B will be of shape (2,3 )")
C = A * B

print(C)
print(A+B)


B shape  (2, 1)
A shape  (2, 3)
after broadcasting B will be of shape (2,3 )
[[ 2  4  6]
 [12 15 18]]
[[3 4 5]
 [7 8 9]]


In [ ]:
a = np.ones((3,3))
b = np.ones((3,3))
c = 3*a

ele_wise = a@b
mat_mul = np.dot(a,c)

print( ele_wise , mat_mul)

[[3. 3. 3.]
 [3. 3. 3.]
 [3. 3. 3.]] [[9. 9. 9.]
 [9. 9. 9.]
 [9. 9. 9.]]
