<a href="https://colab.research.google.com/github/Mrsenjiii/Numpy_reopsitory/blob/main/matrix.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
A = np.array([[1,2],[1,2]])
# A
B = np.array([[2,2],[3,2]])


In [ ]:
A*B

array([[2, 4],
       [3, 4]])

In [ ]:
x = np.array([1,2,3] )
# x.shape
# x.shape[0]
b = np.expand_dims(x, axis = 1)
print(b)
c = np.expand_dims(x , axis = 0)
print(c)
print(c.shape)
b.shape

[[1]
 [2]
 [3]]
[[1 2 3]]
(1, 3)


(3, 1)

In [ ]:
A = np.array([[1,2,3],[4,5,6] ,[7,8,9]])
x = np.array([1,2,3])
# A@x
b = np.expand_dims(x , axis = 1)
b.shape
A@b
b.shape

(3, 1)

In [ ]:
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

In [ ]:
A[ 0:2 ,1]

array([2, 5])